### ISSUE TITLE
Real World Tutorial? 👩‍💻 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-temporal#2]
At present the typescript examples are very isolated and don't show anything real-world:

![image](https://user-images.githubusercontent.com/194400/157840247-92408ad0-8acd-406b-bbe9-cecab36fba55.png)

I would benefit form a real-world example that illustrates the benefits of a Workflow with at least 2 Activities.

# Todo

+ [ ] Create a `Next.js` App that Displays a "Personal Dashboard": 
  + [ ] Inspiring quote
  + [ ] Beautiful picture
  + [ ] Today's weather
+ [ ] Create a Workflow with 3 activities. 
+ [ ] Decide which services to use for the above
+ [ ] Implement the activities
+ [ ] Run them on `localhost`
+ [ ] Render them on a nice page using `next.js`
+ [ ] Deploy the workflow to Heroku or AWS?
+ [ ] Demo it!

**Comment by nelsonic** [comment]
![Temporal_logo](https://user-images.githubusercontent.com/194400/158250447-78d23304-94aa-4850-a8d6-9c3e3815a304.jpeg)
